# development:
#     uri: http://chef:4000/
#     client_name: gecos-kitchen
#     keyfile: config/chef/kitchen.pem    
development:
    uri: https://10.240.194.220/
    client_name: kitchen2
    keyfile: config/chef/kitchen2.pem      

production:
    uri: http://localhost:4000/
    client_name: kitchen
    keyfile: config/chef/kitchen.pem   
    
pre:
    uri: https://10.240.194.220/
    client_name: kitchen2
    keyfile: config/chef/kitchen2.pem
    
    
     