development:
    adapter: mysql
    database: kitchen_development
    username: root
    host: localhost

production:
    adapter: mysql
    database: kitchen_production
    username: root
    host: localhost 
        
test:
    adapter: mysql
    database: kitchen_test
    username: root
    host: localhost

pre:
    adapter: mysql
    database: kitchen_development
    username: root
    host: localhost        